# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TimeSeriesViewingTool
                                 A QGIS plugin
 A tool to view time series images
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-18
        copyright            : (C) 2022 by Chaoying Lin
        email                : 1754129@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TimeSeriesViewingTool class from file TimeSeriesViewingTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .time_series_viewing_tool import TimeSeriesViewingTool
    return TimeSeriesViewingTool(iface)
